#ifndef PASS_PEG_SEARCH_TEST_H
#define PASS_PEG_SEARCH_TEST_H

// Enumerate all 7-letter words in TWL98 whose letters fit a "valid bingo
// rack" for pass-PEG search:
//   - No Q (we reserve a single Q in the unseen pool to keep it
//     unplayable at the root).
//   - No K, J, X, or Z (each has only 1 copy in the English distribution;
//     we need to reserve 2 copies of the rack).
//   - Per-letter count <= floor(distribution_count / 2) so two copies of
//     the rack can be drawn from the bag without exceeding the distribution.
// Outputs the unique sorted-letter signatures (e.g. AEINRST).
void test_pass_peg_enumerate_bingo_racks(void);

// Search for English 1-peg positions where mover_rack + Q = unseen (= a
// "two-copies-of-the-same-bingo-rack-plus-Q" pattern), filtered by the
// rack signatures generated by test_pass_peg_enumerate_bingo_racks. For
// each structural match we also run the user's 5 conditions:
//   1. Mover lead is small (1..25).
//   2. Q is unplayable at the root.
//   3. All mover bingos share the same starting square + direction.
//   4. Every mover bingo allows opp a bingo in response.
//   5. No non-bingo move wins 8/8 of the bag-tile scenarios.
// Stops on first match (controlled by env var PASSPEG_TARGET_COUNT).
void test_pass_peg_search(void);

// Engineered position search: pre-stack the bag by removing 2*R + Q tiles
// at game start, run random autoplay until the board has all 85 remaining
// tiles played (both racks and bag empty at game end), then overwrite the
// racks and bag with R, R, {Q} to produce a 100-tile-LD-consistent 1peg
// state where mover has the bingo R and unseen = R + Q.
//
// Env knobs:
//   PASSPEG_FORCE_RACK     — sorted-letter signature to use (default
//                            "AEINRST"). Overrides the iterate-all-racks
//                            behavior when set.
//   PASSPEG_TARGET_COUNT   — how many positions to find (default 1).
//   PASSPEG_MAX_ATTEMPTS   — random-seed budget (default 200000).
//   PASSPEG_SEED_OFFSET    — first seed (default 1).
void test_pass_peg_engineered_search(void);

// Generate N random 1-in-bag positions (no engineering — straight TWL98
// autoplay) and append CGPs to /tmp/random_1pegs.txt. Env knobs:
//   PASSPEG_RAND_N      — count to generate (default 100)
//   PASSPEG_RAND_SEED   — first seed (default 100001 to avoid clashing
//                         with the engineered candidates' seed range)
void test_pass_peg_generate_random_1pegs(void);

// Generate random positions with target bag size + score-margin filter.
// Env knobs: PASSPEG_RAND_N (count), PASSPEG_RAND_N_BAG (target bag),
// PASSPEG_RAND_LEX (default CSW24), PASSPEG_RAND_MARGIN (max abs margin,
// default 40), PASSPEG_RAND_SEED, PASSPEG_RAND_OUT.
void test_generate_peg_cgps(void);

// Generate a human-readable text report of all bench positions
// (passpeg_candidates.txt + random_1pegs.txt) using
// string_builder_add_game's pretty board view. Annotates each position
// with the bench results from /tmp/passpeg_bench.csv. Writes to
// /tmp/passpeg_report.txt.
void test_pass_peg_print_report(void);

// Oracle-evaluate a fixed candidate move on a 1-in-bag PEG position by
// directly simulating each scenario and running endgame_solve. Useful
// for cross-checking macondo's PEG against MAGPIE on a specific play.
// Configure via env vars:
//   PASSPEG_ORACLE_CGP    — CGP string (default: passpeg position 1).
//   PASSPEG_ORACLE_MOVE   — move string in MAGPIE format, e.g.
//                            "C6.REEST" (default).
//   PASSPEG_ORACLE_PLIES  — endgame plies for the per-scenario solve
//                            (default: 12 for full convergence).
//   PASSPEG_ORACLE_TIME   — soft seconds-per-scenario cap (default: 30).
void test_pass_peg_oracle_eval_move(void);

#endif

void test_pass_peg_greedy_bench(void);
void test_pass_peg_cascade(void);
