#include "pat_hyperscale_fit_test.h"

#include "../src/ent/game.h"
#include "../src/ent/pat.h"
#include "../src/ent/player.h"
#include "../src/impl/config.h"
#include "pat_move_choice_test.h"
#include "test_util.h"
#include <assert.h>

// Tests whether the hypergeometric-scaled hook/float_flex channels
// (pat_dls_champion_v2 has zero weight on them; pat_hyper_frozen_v1, a
// single frozen-policy patgen generation over 150K games -- see that
// commit -- has real trained weight there) actually lead to BETTER move
// choices than the raw-only champion: at each position, get each model's
// own top-equity move, and when they disagree (own-asset-style situations
// are common but most positions still see the two models agree on the
// best play, so most positions carry no signal and are discarded), score
// both candidates under one common, shared reference continuation policy
// and compare.
//
// This file went through two earlier designs, both withdrawn after
// review:
//   1. Compare the champion's top-2 moves' predicted equity against a
//      single Q2 reference generated by the raw champion's own
//      subsequent play. Whole-game autoplay's own noise floor (a
//      40,000-game-pair match came back at 66.6% confidence,
//      indistinguishable from noise) motivated this more direct
//      approach, but scoring the champion's top-2 can simply miss
//      whichever move the scaled model would actually prefer.
//   2. Give each model its OWN Q2, generated by that model's own policy
//      throughout the rollout, and compare each E0 against its own
//      self-consistent target. This reversed design 1's conclusion
//      entirely (raw-significantly-better became scaled-significantly-
//      better), which on review is not a fixed referee bias resolving
//      into truth -- it is answering a different question. "How well
//      does a model predict outcomes under its OWN policy" is a policy-
//      EVALUATION question; a more conservative or more passive policy
//      can be more self-predictable (lower outcome variance) without
//      being a STRONGER policy. Design 2 also reseeded the world only
//      before the opponent's draw, leaving the mover's own post-move
//      refill unpaired across the comparison, and scored raw spread with
//      no leave-value component even though E0 includes one.
// This design instead asks the POLICY-IMPROVEMENT question directly:
// holding the reference continuation fixed and common to both
// candidates, which specific move leads to a better outcome? A common
// reference (here, the unmodified champion) does not carry an opinion
// about which of the two candidates is better, so it does not favor
// either model's own worldview the way design 2's self-consistent
// referee did.
//
// Still a simplified pilot, not Astra (gpt-6-astra)'s full spec: the
// reference continuation is one rollout sample average, not the fully
// independent two-batch product-of-errors estimate needed to remove
// target-sampling-variance contamination from a prediction-error metric
// (moot here, since this design compares REALIZED reference values, not
// predicted-vs-actual error, but the reference value itself is still a
// sampled mean, not an exact expectation); and the world-seed pairing
// (see pat_hyperscale_reference_value) only starts both candidates' bags
// from an identical shuffle, not a true shared, pre-drawn common
// permutation of the unseen pool.

#define PAT_HYPERSCALE_FIT_NUM_POSITIONS 12000
// The "scaled" candidate under test; swapped between retraining attempts
// without touching the rest of the file.
#define PAT_HYPERSCALE_FIT_SCALED_PAT_NAME "pat_hyper_frozen_v1"
#define PAT_LEXFLOAT_PAT_NAME "pat_lexfloat_frozen_v1"
#define PAT_LEGACY_FROZEN_PAT_NAME "pat_legacy_frozen_v1"
#define PAT_SIGNED_PAT_NAME "pat_signed_frozen_v1"
#define PAT_LEXSIGNED_PAT_NAME "pat_lexsigned_frozen_v1"

// Loads a PAT file the way the config path does: pat_create alone leaves
// the lexicon tables (hook_flex, through_score, through_count) empty, and
// a candidate loaded that way disagrees with the same weights fully
// prepared on ~12% of positions (see test_pat_move_choice_targeted_
// controls), which silently handicapped every file-backed candidate in
// this file's earlier runs.
static PATWeights *pat_hyperscale_load(Config *config, const char *name) {
  ErrorStack *error_stack = error_stack_create();
  PATWeights *pat =
      pat_create(config_get_data_paths(config), name, error_stack);
  assert(error_stack_is_empty(error_stack));
  assert(pat);
  error_stack_destroy(error_stack);
  const Game *game = config_get_game(config);
  pat_prepare_hook_flex(pat, player_get_kwg(game_get_player(game, 0)),
                        game_get_ld(game));
  return pat;
}

// Runs the move-choice-benefit comparison of candidate_pat_name against
// baseline_pat_name (NULL for the champion, pat_dls_champion_v2, which is
// the common reference policy either way) over num_positions attempted
// positions seeded from seed_base. Each candidate file gets its own
// prespecified seed range so a confirmation batch never reuses positions
// an earlier exploratory run already looked at.
static void pat_move_choice_benefit(const char *baseline_pat_name,
                                    const char *candidate_pat_name,
                                    uint64_t seed_base, int num_positions,
                                    int num_worlds) {
  Config *config = pat_move_choice_config_create();
  Game *game = config_get_game(config);
  const PATWeights *champion = player_get_pat(game_get_player(game, 0));
  PATWeights *baseline_pat =
      baseline_pat_name ? pat_hyperscale_load(config, baseline_pat_name) : NULL;
  PATWeights *candidate_pat = pat_hyperscale_load(config, candidate_pat_name);
  const PATMoveChooser baseline = {
      .label = baseline_pat_name ? baseline_pat_name : "champion",
      .pat = baseline_pat ? baseline_pat : champion,
      .degrade_margin = 0.0,
      .overlap_correction = 0.0};
  const PATMoveChooser candidate = {.label = candidate_pat_name,
                                    .pat = candidate_pat,
                                    .degrade_margin = 0.0,
                                    .overlap_correction = 0.0};
  PATMoveChoiceResult result;
  pat_move_choice_compare(config, &baseline, &candidate, seed_base,
                          num_positions, num_worlds, &result);
  assert(result.positions_considered > 0);
  pat_destroy(candidate_pat);
  if (baseline_pat) {
    pat_destroy(baseline_pat);
  }
  config_destroy(config);
}

void test_pat_hyperscale_fit(void) {
  pat_move_choice_benefit(NULL, PAT_HYPERSCALE_FIT_SCALED_PAT_NAME,
                          701000000ULL, PAT_HYPERSCALE_FIT_NUM_POSITIONS,
                          PAT_MOVE_CHOICE_DEFAULT_WORLDS);
}

// The lexicon-aware floater refit (pat_lexfloat_frozen_v1: one frozen-
// policy patgen generation over 150K games, seed 4242, from the champion
// with lexicon_floaters,1; see PATWeights.lexicon_floaters) on seed ranges
// no earlier run has used. Two comparisons: against the champion (is it
// better than what ships), and against the identical refit with the flag
// off (pat_legacy_frozen_v1, byte-for-byte pat_hyper_frozen_v1 plus the
// flag row), which isolates the semantics change from the refit itself.
void test_pat_lexfloat_move_choice(void) {
  pat_move_choice_benefit(NULL, PAT_LEXFLOAT_PAT_NAME, 801000000ULL,
                          PAT_HYPERSCALE_FIT_NUM_POSITIONS,
                          PAT_MOVE_CHOICE_DEFAULT_WORLDS);
  pat_move_choice_benefit(PAT_LEGACY_FROZEN_PAT_NAME, PAT_LEXFLOAT_PAT_NAME,
                          811000000ULL, PAT_HYPERSCALE_FIT_NUM_POSITIONS,
                          PAT_MOVE_CHOICE_DEFAULT_WORLDS);
}

// A larger, separately seeded confirmation batch for the isolated
// semantics comparison only: it disagrees on just ~2.4% of positions, so
// the 12,000-position run above resolves it far more coarsely than the
// champion comparison.
void test_pat_lexfloat_isolated_confirm(void) {
  // 200 worlds: the decomposition puts within-position noise near half of
  // Var(mean) at 30, and worlds are cheap next to the exhaustive
  // generation behind each disagreement.
  pat_move_choice_benefit(PAT_LEGACY_FROZEN_PAT_NAME, PAT_LEXFLOAT_PAT_NAME,
                          821000000ULL, 4 * PAT_HYPERSCALE_FIT_NUM_POSITIONS,
                          200);
}

// The signed through-table refit (pat_signed_frozen_v1: the same frozen-
// policy generation from the champion with signed_through,1; see
// PATWeights.signed_through), isolated against the legacy refit and
// against the champion, plus the refit with both lexicon_floaters and
// signed_through on (pat_lexsigned_frozen_v1) against the champion. Fresh
// seed ranges; 100 worlds since within-position noise was near half of
// Var(mean) at 30 and worlds are cheap next to generation.
void test_pat_signed_move_choice_isolated(void) {
  pat_move_choice_benefit(PAT_LEGACY_FROZEN_PAT_NAME, PAT_SIGNED_PAT_NAME,
                          850000000ULL, PAT_HYPERSCALE_FIT_NUM_POSITIONS, 100);
}

void test_pat_signed_move_choice_vs_champion(void) {
  pat_move_choice_benefit(NULL, PAT_SIGNED_PAT_NAME, 851000000ULL,
                          PAT_HYPERSCALE_FIT_NUM_POSITIONS, 100);
}

void test_pat_lexsigned_move_choice_vs_champion(void) {
  pat_move_choice_benefit(NULL, PAT_LEXSIGNED_PAT_NAME, 852000000ULL,
                          PAT_HYPERSCALE_FIT_NUM_POSITIONS, 100);
}
