#ifndef PAT_MOVE_CHOICE_TEST_H
#define PAT_MOVE_CHOICE_TEST_H

#include "../src/ent/pat.h"
#include "../src/impl/config.h"
#include <stdbool.h>
#include <stdint.h>

// One side of a paired move-choice comparison: how the mover picks a move
// at a position. pat is the weights move generation runs under;
// degrade_margin > 0 deliberately picks the best move at least that far
// below the top (a degradation control); overlap_correction != 0 reranks
// the exhaustive list by equity - correction * narrow_overlap(resulting
// board) (see pat_overlap_narrow_measure).
typedef struct PATMoveChooser {
  const char *label;
  const PATWeights *pat;
  double degrade_margin;
  double overlap_correction;
  // != 0: rerank the exhaustive list by equity - pat + pat_scale * pat,
  // i.e. the PAT term rescaled by pat_scale (a stage-scale diagnostic; 1
  // means unchanged and is treated as "not set").
  double pat_scale;
  // When true, this chooser picks as if leave value were zero: the same
  // zero-KLV swap the leave rollout experiment uses
  // (player_set_rollout_zero_klv/player_set_klv in player.h), applied here
  // to a single static move choice instead of rollout forward-play. The
  // caller must attach a zero KLV via player_set_rollout_zero_klv on the
  // mover before this chooser is used (see pat_move_choice_run_leave_spec).
  bool zero_leave;
  // Bitmask of PAT_CLASS_MASK_* (pat.h) premium classes to treat as
  // zero-weighted for this chooser, independent of what pat's own file
  // weights are -- threaded straight into MoveGenArgs.pat_disabled_classes_
  // mask by pat_move_choice_choose. 0 (the default every existing literal
  // gets by omitting this field) disables nothing, i.e. full PAT: matches
  // every chooser's behavior before this field existed.
  uint32_t disabled_classes_mask;
} PATMoveChooser;

typedef struct PATMoveChoiceResult {
  int positions_considered;
  int disagreements;
  double mean;
  double se;
  // Decomposition of the paired world differences d_ir (position i, world
  // r): within is the mean across positions of the sample variance across
  // worlds; between is var(position means) - within / R.
  double within_variance;
  double between_variance;
} PATMoveChoiceResult;

// The champion's own equity player config, with the board loaded.
Config *pat_move_choice_config_create(void);

// The disagreement-scoring leaf: plays move, then reference_pat's own two
// (by default; see pat_move_choice_reference_plies in the .c file) plies of
// reply under a seeded paired world, and returns spread plus each side's
// KLV leave value at the horizon. Shared by any harness that needs to score
// which of two already-chosen moves was actually better under a fixed,
// PAT-independent reference continuation (see the file comment for the
// full rationale). world_seed should differ only in the low bits used to
// pair worlds across the two moves being compared; the same world_seed
// played from two different moves shares its whole random continuation
// until the moves' consequences diverge.
double pat_move_choice_reference_value(const Game *game, const Move *move,
                                       int mover_index,
                                       const PATWeights *reference_pat,
                                       uint64_t world_seed);
// num_worlds reference values, one per world, into values_out (caller-owned,
// at least num_worlds long).
void pat_move_choice_reference_values(const Game *game, const Move *move,
                                      int mover_index,
                                      const PATWeights *reference_pat,
                                      uint64_t base_seed, int num_worlds,
                                      double *values_out);

// Positions are generated by playing a fresh seeded game down to a bag
// size drawn uniformly from [bag_lo, bag_hi] (the champion's own play);
// callers pass PAT_MOVE_CHOICE_DEFAULT_BAG_LO/HI for the usual midgame
// range. num_worlds paired reference worlds per disagreement (at most
// PAT_MOVE_CHOICE_MAX_WORLDS).
void pat_move_choice_compare(Config *config, const PATMoveChooser *baseline,
                             const PATMoveChooser *candidate,
                             uint64_t seed_base, int num_positions,
                             int num_worlds, PATMoveChoiceResult *result_out);
void pat_move_choice_compare_range(Config *config,
                                   const PATMoveChooser *baseline,
                                   const PATMoveChooser *candidate,
                                   uint64_t seed_base, int num_positions,
                                   int num_worlds, int shard, int num_shards,
                                   int bag_lo, int bag_hi,
                                   PATMoveChoiceResult *result_out);

#define PAT_MOVE_CHOICE_DEFAULT_BAG_LO 10
#define PAT_MOVE_CHOICE_DEFAULT_BAG_HI 40

#define PAT_MOVE_CHOICE_MAX_WORLDS 300
// What every comparison used before the decomposition was measured.
#define PAT_MOVE_CHOICE_DEFAULT_WORLDS 30

void pat_move_choice_compare_shard(Config *config,
                                   const PATMoveChooser *baseline,
                                   const PATMoveChooser *candidate,
                                   uint64_t seed_base, int num_positions,
                                   int num_worlds, int shard, int num_shards,
                                   PATMoveChoiceResult *result_out);
void pat_move_choice_run_spec(const char *spec);
// "seed:num_positions:num_worlds" -- real leave vs zeroed leave, same PAT
// champion (production's own -pat) throughout; see the .c file for the
// full comparison. Simpler than pat_move_choice_run_spec's baseline/
// candidate spec strings since there is only ever this one axis.
void pat_move_choice_run_leave_spec(const char *spec);

void test_pat_move_choice_controls(void);
void test_pat_move_choice_targeted_controls(void);
void test_pat_move_choice_tws_only(void);
void test_pat_move_choice_tws_only_ridgefix(void);
void test_pat_train_runtime_parity(void);
void pat_train_runtime_parity_for(const char *pat_name);
void test_pat_leaf_check(void);
void test_pat_through_table_audit(void);
void test_pat_overlap_step3_dev(void);
void test_pat_overlap_step3_confirm(void);

#endif
