#include "pat_hyperscale_fit_test.h"

#include "../src/def/equity_defs.h"
#include "../src/def/game_defs.h"
#include "../src/def/move_defs.h"
#include "../src/def/pat_defs.h"
#include "../src/def/players_data_defs.h"
#include "../src/ent/bag.h"
#include "../src/ent/board.h"
#include "../src/ent/equity.h"
#include "../src/ent/game.h"
#include "../src/ent/letter_distribution.h"
#include "../src/ent/move.h"
#include "../src/ent/pat.h"
#include "../src/ent/player.h"
#include "../src/ent/rack.h"
#include "../src/impl/config.h"
#include "../src/impl/gameplay.h"
#include "../src/impl/move_gen.h"
#include "test_util.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>

// Directly tests whether the hypergeometric-scaled hook/float_flex channels
// (pat_dls_champion_v2 has zero weight on them; pat_hyper_frozen_v1, a
// single frozen-policy patgen generation over 150K games -- see that
// commit -- has real trained weight there) predict real two-ply outcomes
// better than the raw-only champion, reusing the position generation and
// rollout machinery from pat_asset_fit_test.c. Much more direct than a
// whole-game autoplay match: whole-game win rate has to resolve a small
// per-move effect through a huge amount of unrelated variance (the exact
// problem that made the earlier 40,000-game-pair autoplay match against
// this same file come back at 66.6% confidence, indistinguishable from
// noise), where comparing predicted-vs-actual outcome on the same
// candidate pairs isolates the one thing that changed between the two
// files instead of drowning it in whichever side drew the better bag.
//
// Simpler than pat_asset_fit_test.c's pair selection: hook/floater
// features are live on most midgame positions with any open premium
// square (unlike own-asset eligibility, which needed a specific leave/hook
// letter match), so an arbitrary top-2 pair is expected to carry signal
// often enough without scanning for one that differs.
//
// Each model's Q2 is generated by its OWN policy (see
// pat_hyperscale_fit_rollout_spread): an earlier version shared one Q2
// (always under the raw champion's own move choices) between both models'
// error terms, which is a referee bias, not a neutral ground truth --
// it can only validate a model whose own preferences happen to agree
// with the referee policy's. A model whose improved evaluation would
// also change its OWN subsequent-ply choices can never get credit for
// that under a fixed foreign referee.

#define PAT_HYPERSCALE_FIT_NUM_POSITIONS 12000
#define PAT_HYPERSCALE_FIT_MOVE_LIST_CAPACITY 500
// The "scaled" candidate under test; swapped between retraining attempts
// (e.g. different ridge lambdas) without touching the rest of the file.
#define PAT_HYPERSCALE_FIT_SCALED_PAT_NAME "pat_hyper_frozen_v1"
// Rollout samples averaged per candidate move, each one paired against the
// other candidate's same-index sample via a shared world_seed (see
// pat_hyperscale_fit_rollout_spread). A single sample's noise floor (SD
// ~33 points, from the unpaired v1 run) swamped any real difference
// between the raw and scaled models; averaging N independent (but per-
// index paired) samples divides that noise's variance by N.
#define PAT_HYPERSCALE_FIT_NUM_ROLLOUT_SAMPLES 30

// One context per (position, weights file), reused for both candidate
// moves: it depends on the board and unseen tiles, never on which move is
// later scored against it.
static void pat_hyperscale_fit_load_context(const Game *game,
                                            const PATWeights *weights,
                                            int mover_index,
                                            PATEvalContext *ctx_out) {
  const Player *mover = game_get_player(game, mover_index);
  const LetterDistribution *ld = game_get_ld(game);
  const Board *board = game_get_board(game);
  const int cross_set_index = board_get_cross_set_index(
      game_get_data_is_shared(game, PLAYERS_DATA_TYPE_KWG), mover_index);
  const Rack *opponent_rack =
      player_get_rack(game_get_player(game, 1 - mover_index));
  pat_eval_context_load(ctx_out, weights,
                        board_get_readonly_lanes(board, cross_set_index), ld,
                        player_get_rack(mover), PAT_CLASS_MASK_ALL,
                        rack_get_total_letters(opponent_rack));
}

// Plays move on a duplicate of game, then samples one hypothetical
// continuation (a uniformly random opponent rack, the opponent's own
// top-equity reply, and the mover's own top-equity reply after that) and
// returns the resulting spread from the mover's side.
//
// rollout_pat is loaded onto BOTH of the duplicate's players (via
// player_set_pat) before either reply is chosen, so the whole rollout's
// own move choices are self-consistent with whichever model this
// particular Q2 is meant to validate. This matters: a rollout whose own
// subsequent-ply choices always follow one fixed policy (e.g. always the
// raw champion) can only ever validate models that happen to agree with
// that policy's own worldview -- it is not a policy-neutral referee, and
// scoring a different model's E0 against outcomes generated by a
// mismatched policy's choices structurally disadvantages that model
// regardless of whether its own evaluation is actually better. Each
// candidate move therefore gets its own Q2 under its own model's policy,
// not one shared Q2 compared against two different E0s.
//
// world_seed reseeds the bag's PRNG (game_seed -> bag_seed, which
// reshuffles whatever is currently in the bag; it touches no other game
// state) immediately before the opponent's random draw, and is the same
// value for both candidates (and both policies) at one position and
// sample index: candidate a's and b's post-move bags differ (they used
// different tiles), so this does not draw the identical physical rack
// for both, but it does apply the identical shuffle to each of their own
// bags, correlating the draws' luck instead of leaving them fully
// independent -- a partial version of Astra's shared-world pairing, not
// the exact conditioned draw a fixed, common unseen-pool permutation
// would give, but a real reduction in the noise floor that was swamping
// both this and the own-asset pilot.
static int pat_hyperscale_fit_rollout_spread(const Game *game, const Move *move,
                                             int mover_index,
                                             const PATWeights *rollout_pat,
                                             uint64_t world_seed) {
  Game *rollout_game = game_duplicate(game);
  player_set_pat(game_get_player(rollout_game, 0), rollout_pat);
  player_set_pat(game_get_player(rollout_game, 1), rollout_pat);
  play_move(move, rollout_game, NULL);
  const int opponent_index = 1 - mover_index;
  if (game_get_game_end_reason(rollout_game) == GAME_END_REASON_NONE) {
    game_seed(rollout_game, world_seed);
    set_random_rack(rollout_game, opponent_index, NULL);
    MoveList *reply_list = move_list_create(1);
    const Move *opponent_reply = get_top_equity_move(rollout_game, reply_list);
    play_move(opponent_reply, rollout_game, NULL);
    move_list_destroy(reply_list);
  }
  if (game_get_game_end_reason(rollout_game) == GAME_END_REASON_NONE) {
    MoveList *reply_list = move_list_create(1);
    const Move *mover_reply = get_top_equity_move(rollout_game, reply_list);
    play_move(mover_reply, rollout_game, NULL);
    move_list_destroy(reply_list);
  }
  const Equity spread =
      player_get_score(game_get_player(rollout_game, mover_index)) -
      player_get_score(game_get_player(rollout_game, opponent_index));
  game_destroy(rollout_game);
  return equity_to_int(spread);
}

// Mean of PAT_HYPERSCALE_FIT_NUM_ROLLOUT_SAMPLES independent rollouts, each
// sample index using the same world_seed as the same-index call for
// whichever other candidate/policy this move is being compared against
// (the caller passes the same base_seed for every one of the up-to-four
// calls at one position), pairing every individual sample, not just the
// aggregate.
static double pat_hyperscale_fit_average_rollout(const Game *game,
                                                 const Move *move,
                                                 int mover_index,
                                                 const PATWeights *rollout_pat,
                                                 uint64_t base_seed) {
  double total = 0.0;
  for (int sample_idx = 0; sample_idx < PAT_HYPERSCALE_FIT_NUM_ROLLOUT_SAMPLES;
       sample_idx++) {
    const uint64_t world_seed =
        base_seed + (uint64_t)sample_idx * 1000003ULL; // a prime stride
    total += (double)pat_hyperscale_fit_rollout_spread(game, move, mover_index,
                                                       rollout_pat, world_seed);
  }
  return total / PAT_HYPERSCALE_FIT_NUM_ROLLOUT_SAMPLES;
}

void test_pat_hyperscale_fit(void) {
  Config *config = config_create_or_die(
      "set -lex CSW21 -s1 equity -s2 equity -r1 all -r2 all -numplays 1 "
      "-pat pat_dls_champion_v2");
  load_and_exec_config_or_die(
      config, "cgp 15/15/15/15/15/15/15/15/15/15/15/15/15/15/15 / 0/0 0");
  Game *game = config_get_game(config);
  const PATWeights *raw_pat = player_get_pat(game_get_player(game, 0));
  assert(raw_pat);

  ErrorStack *error_stack = error_stack_create();
  PATWeights *scaled_pat =
      pat_create(config_get_data_paths(config),
                 PAT_HYPERSCALE_FIT_SCALED_PAT_NAME, error_stack);
  assert(error_stack_is_empty(error_stack));
  assert(scaled_pat);
  error_stack_destroy(error_stack);

  MoveList *candidate_list =
      move_list_create(PAT_HYPERSCALE_FIT_MOVE_LIST_CAPACITY);
  MoveList *setup_move_list = move_list_create(1);

  double squared_error_raw = 0.0;
  double squared_error_scaled = 0.0;
  // Paired per-position difference (scaled's squared error minus raw's):
  // negative means scaled did better on that specific pair. Tracked so a
  // real paired t-statistic can be reported, not just the aggregate MSEs,
  // which a few outlier positions could otherwise dominate.
  double sum_paired_diff = 0.0;
  double sum_paired_diff_sq = 0.0;
  int num_pairs = 0;

  for (int attempt = 0; attempt < PAT_HYPERSCALE_FIT_NUM_POSITIONS; attempt++) {
    const uint64_t seed = 700000000ULL + (uint64_t)attempt;
    game_reset(game);
    game_seed(game, seed);
    draw_starting_racks(game);
    const int target_bag = 10 + (int)(seed % 31); // spans [10, 40]
    bool position_ok = true;
    while (bag_get_letters(game_get_bag(game)) > target_bag) {
      const Move *setup_move = get_top_equity_move(game, setup_move_list);
      play_move(setup_move, game, NULL);
      if (game_get_game_end_reason(game) != GAME_END_REASON_NONE) {
        position_ok = false;
        break;
      }
    }
    if (!position_ok || bag_get_letters(game_get_bag(game)) == 0) {
      continue;
    }
    const Board *board = game_get_board(game);
    if (board_get_transposed(board) || !board_get_cross_sets_valid(board)) {
      continue;
    }

    const int mover_index = game_get_player_on_turn_index(game);
    const MoveGenArgs args = {
        .game = game,
        .move_list = candidate_list,
        .move_record_type = MOVE_RECORD_ALL,
        .move_sort_type = MOVE_SORT_EQUITY,
        .override_kwg = NULL,
        .eq_margin_movegen = 0,
        .target_equity = EQUITY_MAX_VALUE,
        .target_leave_size_for_exchange_cutoff = UNSET_LEAVE_SIZE,
    };
    generate_moves(&args);
    move_list_sort_moves(candidate_list);
    if (move_list_get_count(candidate_list) < 2) {
      continue;
    }
    const Move *move_a = move_list_get_move(candidate_list, 0);
    const Move *move_b = move_list_get_move(candidate_list, 1);
    if (move_get_type(move_a) != GAME_EVENT_TILE_PLACEMENT_MOVE ||
        move_get_type(move_b) != GAME_EVENT_TILE_PLACEMENT_MOVE) {
      continue;
    }

    Rack leave_a;
    Rack leave_b;
    get_leave_for_move(move_a, game, &leave_a);
    get_leave_for_move(move_b, game, &leave_b);
    // Under the champion's own weights, move_get_equity is already the
    // full score+leave+PAT equity movegen recorded -- E0_raw for free.
    const double e0_raw_a = equity_to_double(move_get_equity(move_a));
    const double e0_raw_b = equity_to_double(move_get_equity(move_b));

    PATEvalContext ctx_raw;
    PATEvalContext ctx_scaled;
    pat_hyperscale_fit_load_context(game, raw_pat, mover_index, &ctx_raw);
    pat_hyperscale_fit_load_context(game, scaled_pat, mover_index, &ctx_scaled);
    // E0_scaled differs from E0_raw only in the PAT term (score and leave
    // value do not depend on which PAT file is loaded), so it is E0_raw
    // plus the delta between the two files' PAT terms for the same move.
    const double pat_delta_a =
        equity_to_double(pat_eval_move_penalty(&ctx_scaled, move_a, &leave_a)) -
        equity_to_double(pat_eval_move_penalty(&ctx_raw, move_a, &leave_a));
    const double pat_delta_b =
        equity_to_double(pat_eval_move_penalty(&ctx_scaled, move_b, &leave_b)) -
        equity_to_double(pat_eval_move_penalty(&ctx_raw, move_b, &leave_b));
    const double e0_scaled_a = e0_raw_a + pat_delta_a;
    const double e0_scaled_b = e0_raw_b + pat_delta_b;

    Move move_a_copy;
    Move move_b_copy;
    move_copy(&move_a_copy, move_a);
    move_copy(&move_b_copy, move_b);
    const uint64_t world_seed = seed + 500000000ULL;
    // Each model gets its own Q2, generated by its own policy throughout
    // the rollout (see pat_hyperscale_fit_rollout_spread) -- not one
    // shared Q2 judged by a single, possibly mismatched, referee policy.
    const double q2_raw_a = pat_hyperscale_fit_average_rollout(
        game, &move_a_copy, mover_index, raw_pat, world_seed);
    const double q2_raw_b = pat_hyperscale_fit_average_rollout(
        game, &move_b_copy, mover_index, raw_pat, world_seed);
    const double q2_scaled_a = pat_hyperscale_fit_average_rollout(
        game, &move_a_copy, mover_index, scaled_pat, world_seed);
    const double q2_scaled_b = pat_hyperscale_fit_average_rollout(
        game, &move_b_copy, mover_index, scaled_pat, world_seed);

    const double error_raw = (q2_raw_a - q2_raw_b) - (e0_raw_a - e0_raw_b);
    const double error_scaled =
        (q2_scaled_a - q2_scaled_b) - (e0_scaled_a - e0_scaled_b);
    squared_error_raw += error_raw * error_raw;
    squared_error_scaled += error_scaled * error_scaled;
    const double paired_diff =
        error_scaled * error_scaled - error_raw * error_raw;
    sum_paired_diff += paired_diff;
    sum_paired_diff_sq += paired_diff * paired_diff;
    num_pairs++;
  }

  move_list_destroy(candidate_list);
  move_list_destroy(setup_move_list);
  pat_destroy(scaled_pat);

  const double mse_raw = num_pairs > 0 ? squared_error_raw / num_pairs : 0.0;
  const double mse_scaled =
      num_pairs > 0 ? squared_error_scaled / num_pairs : 0.0;
  printf("\nhyperscale fit pilot (%d rollout samples per candidate): %d "
         "pairs\n",
         PAT_HYPERSCALE_FIT_NUM_ROLLOUT_SAMPLES, num_pairs);
  printf("raw-only (champion) MSE against 2-ply reference:    %.6f\n", mse_raw);
  printf("hypergeometric-scaled MSE against 2-ply reference:  %.6f\n",
         mse_scaled);
  printf("%s\n", mse_scaled < mse_raw
                     ? "scaled model predicts real outcomes better"
                     : "scaled model does not predict real outcomes better");
  if (num_pairs > 1) {
    const double mean_diff = sum_paired_diff / num_pairs;
    const double variance_diff =
        (sum_paired_diff_sq / num_pairs - mean_diff * mean_diff) *
        ((double)num_pairs / (num_pairs - 1));
    const double se_diff = sqrt(variance_diff / num_pairs);
    const double t_stat = se_diff > 0.0 ? mean_diff / se_diff : 0.0;
    printf("paired diff (scaled_sq_err - raw_sq_err): mean %.4f, SE %.4f, "
           "t = %.3f (negative t means scaled is significantly better; "
           "|t| > ~2 is roughly significant at this sample size)\n",
           mean_diff, se_diff, t_stat);
  }

  assert(num_pairs > 0);
  config_destroy(config);
}
