#ifndef INFERENCE_DEFS_H
#define INFERENCE_DEFS_H

#define INFERENCE_EQUITY_EPSILON 0.000000001
// FIXME: probably make this an enum
#define INFERENCE_SUBTOTAL_INDEX_OFFSET_DRAW 0
#define INFERENCE_SUBTOTAL_INDEX_OFFSET_LEAVE 1

typedef enum {
  INFERENCE_STATUS_SUCCESS,
  INFERENCE_STATUS_NO_TILES_PLAYED,
  INFERENCE_STATUS_RACK_OVERFLOW,
  INFERENCE_STATUS_TILES_PLAYED_NOT_IN_BAG,
  INFERENCE_STATUS_BOTH_PLAY_AND_EXCHANGE,
  INFERENCE_STATUS_EXCHANGE_SCORE_NOT_ZERO,
  INFERENCE_STATUS_EXCHANGE_NOT_ALLOWED,
} inference_status_t;

#endif