#ifndef MOVEGEN_DEFS_H
#define MOVEGEN_DEFS_H

#define OPENING_HOTSPOT_PENALTY -0.7
#define PREENDGAME_ADJUSTMENT_VALUES_LENGTH 13
#define DEFAULT_BINGO_BONUS 50
#define NON_OUTPLAY_LEAVE_SCORE_MULTIPLIER_PENALTY 2.0
#define NON_OUTPLAY_CONSTANT_PENALTY 10.0

#endif
