#ifndef AUTOPLAY_DEFS_H
#define AUTOPLAY_DEFS_H

typedef enum {
  AUTOPLAY_TYPE_DEFAULT,
  AUTOPLAY_TYPE_LEAVE_GEN,
} autoplay_t;

typedef enum {
  MULTI_THREADING_MODE_PER_GAME_PARALLELISM,
  MULTI_THREADING_MODE_INTRA_GAME_PARALLELISM,
} multi_threading_mode_t;

#define MULTI_THREADING_MODE_PER_GAME_PARALLELISM_STRING "pgp"
#define MULTI_THREADING_MODE_INTRA_GAME_PARALLELISM_STRING "igp"

#endif