#ifndef AUTOPLAY_DEFS_H
#define AUTOPLAY_DEFS_H

typedef enum {
  AUTOPLAY_TYPE_DEFAULT,
  AUTOPLAY_TYPE_LEAVE_GEN,
} autoplay_t;

typedef enum {
  AUTOPLAY_STATUS_SUCCESS,
  AUTOPLAY_STATUS_EMPTY_OPTIONS,
  AUTOPLAY_STATUS_INVALID_OPTIONS,
  AUTOPLAY_STATUS_MALFORMED_MINIMUM_LEAVE_TARGETS,
  AUTOPLAY_STATUS_MALFORMED_NUM_GAMES,
} autoplay_status_t;

#endif