#ifndef CROSS_SET_DEFS_H
#define CROSS_SET_DEFS_H

#define WORD_DIRECTION_RIGHT 1
#define WORD_DIRECTION_LEFT -1
#define SEPARATION_MACHINE_LETTER 0
#define TRIVIAL_CROSS_SET (uint64_t)((uint64_t)1 << MAX_ALPHABET_SIZE) - 1

#endif
