#ifndef ERROR_STATUS_DEFS_H
#define ERROR_STATUS_DEFS_H

typedef enum {
  ERROR_STATUS_TYPE_NONE,
  ERROR_STATUS_TYPE_CONFIG_LOAD,
  ERROR_STATUS_TYPE_CGP_LOAD,
  ERROR_STATUS_TYPE_SIM,
  ERROR_STATUS_TYPE_INFER,
  ERROR_STATUS_TYPE_AUTOPLAY,
} error_status_t;

#endif