#ifndef GAME_DEFS_H
#define GAME_DEFS_H

#define GAME_VARIANT_UNKNOWN_NAME "unknown"
#define GAME_VARIANT_CLASSIC_NAME "classic"
#define GAME_VARIANT_WORDSMOG_NAME "wordsmog"

#define MAX_SEARCH_DEPTH 25
#define MAX_SCORELESS_TURNS 6

typedef enum {
  GAME_VARIANT_UNKNOWN,
  GAME_VARIANT_CLASSIC,
  GAME_VARIANT_WORDSMOG,
} game_variant_t;

typedef enum {
  BACKUP_MODE_OFF,
  BACKUP_MODE_SIMULATION,
} backup_mode_t;

typedef enum {
  GAME_END_REASON_NONE,
  GAME_END_REASON_STANDARD,
  GAME_END_REASON_CONSECUTIVE_ZEROS,
  NUMBER_OF_GAME_END_REASONS,
} game_end_reason_t;

#endif