#ifndef GAMEPLAY_DEFS_H
#define GAMEPLAY_DEFS_H

typedef enum {
  MOVE_PARSE_STATUS_SUCCESS,
  MOVE_PARSE_STATUS_MALFORMED,
  MOVE_PARSE_STATUS_DISCONNECTED,
  MOVE_PARSE_STATUS_OUT_OF_BOUNDS,
  MOVE_PARSE_STATUS_TILES_NOT_IN_RACK,
  MOVE_PARSE_STATUS_PHONY,
} move_parse_status_t;

#endif