#ifndef GAME_DEFS_H
#define GAME_DEFS_H

#define GAME_VARIANT_CLASSIC_NAME "classic"
#define GAME_VARIANT_WORDSMOG_NAME "wordsmog"

#define MAX_SEARCH_DEPTH 25
#define MAX_SCORELESS_TURNS 6

typedef enum {
  GAME_VARIANT_UNKNOWN,
  GAME_VARIANT_CLASSIC,
  GAME_VARIANT_WORDSMOG,
} game_variant_t;

typedef enum {
  BACKUP_MODE_OFF,
  BACKUP_MODE_SIMULATION,
} backup_mode_t;

typedef enum {
  CGP_PARSE_STATUS_SUCCESS,
  CGP_PARSE_STATUS_MISSING_REQUIRED_FIELDS,
  CGP_PARSE_STATUS_INVALID_NUMBER_OF_BOARD_ROWS,
  CGP_PARSE_STATUS_INVALID_NUMBER_OF_BOARD_COLUMNS,
  CGP_PARSE_STATUS_INVALID_NUMBER_OF_PLAYER_RACKS,
  CGP_PARSE_STATUS_INVALID_NUMBER_OF_PLAYER_SCORES,
  CGP_PARSE_STATUS_MALFORMED_BOARD_LETTERS,
  CGP_PARSE_STATUS_MALFORMED_SCORES,
  CGP_PARSE_STATUS_MALFORMED_RACK_LETTERS,
  CGP_PARSE_STATUS_MALFORMED_CONSECUTIVE_ZEROS,
  CGP_PARSE_STATUS_MALFORMED_CGP_OPCODE_BINGO_BONUS,
  CGP_PARSE_STATUS_MALFORMED_CGP_OPCODE_BOARD_NAME,
  CGP_PARSE_STATUS_MALFORMED_CGP_OPCODE_GAME_VARIANT,
} cgp_parse_status_t;

typedef enum {
  GAME_END_REASON_NONE,
  GAME_END_REASON_STANDARD,
  GAME_END_REASON_CONSECUTIVE_ZEROS,
} game_end_reason_t;

#endif