#ifndef KLV_DEFS_H
#define KLV_DEFS_H

enum {
  KLV_UNFOUND_INDEX = 0xFFFFFFFFU,
  KLV3_EARLIEST_SUPPORTED_VERSION = 1,
  KLV3_VERSION = 2,
  KLV3_DRAW_COUNT_HEADS = 8,
  KLV3_MAX_POOL_SIZE_BINS = 16,
  KLV3_CAP_QUANTILE_SCALE = 1000000,
};

#endif
