#ifndef LEAVE_GEN_DEFS_H
#define LEAVE_GEN_DEFS_H

typedef enum {
  LEAVE_GEN_STATUS_SUCCESS,
  LEAVE_GEN_STATUS_DIFFERENT_LEXICA_OR_LEAVES,
  LEAVE_GEN_STATUS_INVALID_CREATE_OR_REFINE_OPTION,
} leave_gen_status_t;

#endif