#ifndef LETTER_DISTRIBUTION_DEFS_H
#define LETTER_DISTRIBUTION_DEFS_H

#include <stdint.h>

typedef uint8_t MachineLetter;

enum {
  ALPHABET_EMPTY_SQUARE_MARKER = 0,
  PLAYED_THROUGH_MARKER = 0,
  BLANK_MACHINE_LETTER = 0,
  BLANK_MASK = 0x80,
  UNBLANK_MASK = (0x80 - 1),
  MAX_ALPHABET_SIZE = 50,
  MACHINE_LETTER_MAX_VALUE = (MAX_ALPHABET_SIZE + BLANK_MASK),
  MAX_LETTER_BYTE_LENGTH = 6,
  ASCII_PLAYED_THROUGH = '.',
};

#define ENGLISH_LETTER_DISTRIBUTION_NAME "english"
#define GERMAN_LETTER_DISTRIBUTION_NAME "german"
#define NORWEGIAN_LETTER_DISTRIBUTION_NAME "norwegian"
#define CATALAN_LETTER_DISTRIBUTION_NAME "catalan"
#define POLISH_LETTER_DISTRIBUTION_NAME "polish"
#define DUTCH_LETTER_DISTRIBUTION_NAME "dutch"
#define FRENCH_LETTER_DISTRIBUTION_NAME "french"
#define SUPER_LETTER_DISTRIBUTION_NAME_EXTENSION "super"

#endif
