#ifndef PLAYERS_DATA_DEFS_H
#define PLAYERS_DATA_DEFS_H

typedef enum {
  PLAYERS_DATA_TYPE_KWG,
  PLAYERS_DATA_TYPE_KLV,
  PLAYERS_DATA_TYPE_WMP,
  PLAYERS_DATA_TYPE_UNSORTED_WORDS,
  NUMBER_OF_DATA
} players_data_t;

#endif
