#ifndef RACK_DEFS_H
#define RACK_DEFS_H

#define RACK_SIZE 7
#define ROUND_UP_TO_NEXT_MULTIPLE_OF_8(x) (((x) + 7) & ~7)
#define WORD_ALIGNING_RACK_SIZE ROUND_UP_TO_NEXT_MULTIPLE_OF_8(RACK_SIZE)
#define MAX_RACK_SIZE 10000

#endif