#ifndef THREAD_CONTROL_DEFS_H
#define THREAD_CONTROL_DEFS_H

typedef enum {
  CHECK_STOP_INACTIVE,
  CHECK_STOP_ACTIVE,
} check_stop_status_t;

typedef enum {
  MODE_STOPPED,
  MODE_SEARCHING,
} mode_search_status_t;

typedef enum {
  EXIT_STATUS_NONE,
  // FIXME: remove probabilistic enum
  EXIT_STATUS_PROBABILISTIC,
  EXIT_STATUS_MAX_ITERATIONS,
  EXIT_STATUS_USER_INTERRUPT,
  EXIT_STATUS_THRESHOLD,
  EXIT_STATUS_SAMPLE_LIMIT,
  EXIT_STATUS_TIME_LIMIT,
  EXIT_STATUS_USER_INTERRUPT,
  EXIT_STATUS_ONE_ARM_REMAINING,
} exit_status_t;

#define MAX_THREADS 512

#endif