#ifndef VALIDATED_MOVE_DEFS_H
#define VALIDATED_MOVE_DEFS_H

typedef enum {
  MOVE_VALIDATION_STATUS_SUCCESS,
  MOVE_VALIDATION_STATUS_NULL_INPUT,
  MOVE_VALIDATION_STATUS_INVALID_PLAYER_INDEX,
  MOVE_VALIDATION_STATUS_MISSING_FIELDS,
  MOVE_VALIDATION_STATUS_DISCONNECTED,
  MOVE_VALIDATION_STATUS_OUT_OF_BOUNDS,
  MOVE_VALIDATION_STATUS_TILES_OVERLAP,
  MOVE_VALIDATION_STATUS_TILES_NOT_IN_RACK,
  MOVE_VALIDATION_STATUS_PHONY,
} move_validation_status_t;

#define UCGI_PASS_MOVE "pass"
#define UCGI_EXCHANGE_MOVE "ex"

#endif