#ifndef VALIDATED_MOVE_DEFS_H
#define VALIDATED_MOVE_DEFS_H

typedef enum {
  MOVE_VALIDATION_STATUS_SUCCESS,
  MOVE_VALIDATION_STATUS_MALFORMED,
  MOVE_VALIDATION_STATUS_DISCONNECTED,
  MOVE_VALIDATION_STATUS_OUT_OF_BOUNDS,
  MOVE_VALIDATION_STATUS_TILES_NOT_IN_RACK,
  MOVE_VALIDATION_STATUS_PHONY,
} move_validation_status_t;

#endif