#ifndef WMP_DEFS_H
#define WMP_DEFS_H

enum {
  WMP_INLINE_VALUE_BYTES = 16,
  WMP_NONINLINE_PADDING_BYTES =
      WMP_INLINE_VALUE_BYTES - 2 * sizeof(uint32_t) - 1,
  WMP_QUOTIENT_BYTES = 12,
  WMP_BUCKET_ITEMS_CAPACITY = 1,
  WMP_EARLIEST_SUPPORTED_VERSION = 2,
  WMP_VERSION = 2,
  WMP_RESULT_BUFFER_SIZE = 7000,
};

#endif
