#ifndef WMP_DEFS_H
#define WMP_DEFS_H

#define WMP_INLINE_VALUE_BYTES 16
#define WMP_NONINLINE_PADDING_BYTES \
  WMP_INLINE_VALUE_BYTES - 2 * sizeof(uint32_t) - 1
#define WMP_QUOTIENT_BYTES 12

#define WMP_BUCKET_ITEMS_CAPACITY 1

#define WMP_EARLIEST_SUPPORTED_VERSION 2
#define WMP_VERSION 2

#define WMP_RESULT_BUFFER_SIZE 7000

#endif
