#ifndef WMP_DEFS_H
#define WMP_DEFS_H

#define WMP_INLINE_VALUE_BYTES 16
#define WMP_QUOTIENT_BYTES 12

#define WORD_MAP_BUCKET_ITEMS_CAPACITY 1

#define WORD_MAP_EARLIEST_SUPPORTED_VERSION 1
#define WORD_MAP_VERSION 1
#define WORD_MAP_INLINE_VALUE_BYTES 16
#define WORD_MAP_WORD_START_OFFSET_BYTES 8
#define WORD_MAP_BLANK_LETTERS_OFFSET_BYTES 8
#define WORD_MAP_NUM_WORDS_OFFSET_BYTES 12
#define WORD_MAP_QUOTIENT_BYTES 12

#endif