#ifndef WORD_MAP_DEFS_H
#define WORD_MAP_DEFS_H

#define WORD_MAP_BUCKET_ITEMS_CAPACITY 1

#define WORD_MAP_MAJOR_VERSION 0
#define WORD_MAP_MINOR_VERSION 0
#define WORD_MAP_INLINE_VALUE_BYTES 16
#define WORD_MAP_WORD_START_BYTES 4
#define WORD_MAP_NUM_WORD_BYTES 4
#define WORD_MAP_QUOTIENT_BYTES 12
#define WORD_MAP_WORDS_OFFSET_BYTES 4

#endif