#ifndef WORD_MAP_DEFS_H
#define WORD_MAP_DEFS_H

enum {
  WORD_MAP_BUCKET_ITEMS_CAPACITY = 1,
  WORD_MAP_MAJOR_VERSION = 0,
  WORD_MAP_MINOR_VERSION = 0,
  WORD_MAP_INLINE_VALUE_BYTES = 16,
  WORD_MAP_WORD_START_BYTES = 4,
  WORD_MAP_NUM_WORD_BYTES = 4,
  WORD_MAP_WORDS_OFFSET_BYTES = 4
};

#endif