
#ifndef GCG_H
#define GCG_H

#include "game_history.h"

typedef enum {
  GCG_PARSE_STATUS_SUCCESS,
  GCG_PARSE_STATUS_DUPLICATE_NAMES,
  GCG_PARSE_STATUS_DUPLICATE_NICKNAMES,
  GCG_PARSE_STATUS_PRAGMA_SUCCEEDED_EVENT,
  GCG_PARSE_STATUS_ENCODING_WRONG_PLACE,
  GCG_PARSE_STATUS_PLAYER_DOES_NOT_EXIST,
  GCG_PARSE_STATUS_PLAYER_NUMBER_REDUNDANT,
  GCG_PARSE_STATUS_LINE_OVERFLOW,
  GCG_PARSE_STATUS_UNSUPPORTED_CHARACTER_ENCODING,
  GCG_PARSE_STATUS_GCG_EMPTY,
  GCG_PARSE_STATUS_NOTE_PRECEDENT_EVENT,
  GCG_PARSE_STATUS_NO_MATCHING_TOKEN,
  GCG_PARSE_STATUS_PHONY_TILES_RETURNED_WITHOUT_PLAY,
  GCG_PARSE_STATUS_LAST_RACK_PENALTY_MALFORMED,
  GCG_PARSE_STATUS_RACK_MALFORMED,
  GCG_PARSE_STATUS_INVALID_TILE_PLACEMENT_POSITION,
  GCG_PARSE_STATUS_MOVE_BEFORE_PLAYER,
} gcg_parse_status_t;

gcg_parse_status_t parse_gcg(const char *gcg_filename,
                             GameHistory *game_history);
gcg_parse_status_t parse_gcg_string(const char *input_gcg_string,
                                    GameHistory *game_history);

#endif
